"""Add chat_history table

Revision ID: 8b87b48a83f2
Revises: 38614cce7050
Create Date: 2026-06-30 22:52:15.709116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b87b48a83f2'
down_revision: Union[str, Sequence[str], None] = '38614cce7050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chathistory',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('message_content', sa.String(), nullable=False),
        sa.Column('response_content', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('intent_classified', sa.String(), nullable=True),
        sa.Column('extracted_entities', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chathistory')
    # ### end Alembic commands ###
